// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Abstract: typeof import('./src/components/NewDoc/Abstract.vue')['default']
    AddFeatureButton: typeof import('./src/components/atoms/AddFeatureButton.vue')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    Categories: typeof import('./src/components/NewDoc/Categories.vue')['default']
    DisplayFeature: typeof import('./src/components/molecules/DisplayFeature.vue')['default']
    Editor: typeof import('./src/components/molecules/Editor.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    'Ic:outlineAddCircleOutline': typeof import('virtual:vite-icons/ic/outline-add-circle-outline')['default']
    'Ic:roundCheck': typeof import('virtual:vite-icons/ic/round-check')['default']
    'Ic:roundDeleteOutline': typeof import('virtual:vite-icons/ic/round-delete-outline')['default']
    'Ic:roundKeyboardArrowDown': typeof import('virtual:vite-icons/ic/round-keyboard-arrow-down')['default']
    'Ic:roundKeyboardArrowUp': typeof import('virtual:vite-icons/ic/round-keyboard-arrow-up')['default']
    'Ic:roundLock': typeof import('virtual:vite-icons/ic/round-lock')['default']
    'Ic:roundMailOutline': typeof import('virtual:vite-icons/ic/round-mail-outline')['default']
    'Ic:sharpVisibility': typeof import('virtual:vite-icons/ic/sharp-visibility')['default']
    'Ic:sharpVisibilityOff': typeof import('virtual:vite-icons/ic/sharp-visibility-off')['default']
    'IcomoonFree:books': typeof import('virtual:vite-icons/icomoon-free/books')['default']
    InputLabel: typeof import('./src/components/atoms/InputLabel.vue')['default']
    Modal: typeof import('./src/components/molecules/Modal.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Notes: typeof import('./src/components/NewDoc/Notes.vue')['default']
    Quotes: typeof import('./src/components/NewDoc/Quotes.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    ReadOnlyEditor: typeof import('./src/components/molecules/ReadOnlyEditor.vue')['default']
    Reference: typeof import('./src/components/NewDoc/Reference.vue')['default']
    Review: typeof import('./src/components/NewDoc/Review.vue')['default']
  }
}

export { }
