// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    'IcomoonFree:books': typeof import('virtual:vite-icons/icomoon-free/books')['default']
    InputLabel: typeof import('./src/components/atoms/InputLabel.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    README: typeof import('./src/components/README.md')['default']
  }
}

export { }
